info:
    application:
        name: TimeManager
        description: TimeManagerAPI
        author: Nikik0
        version: '@project.version@'
spring:
    profiles:
        active: dev
    jpa:
        properties:
            hibernate:
                jdbc:
                    batch_size: 100

